/*INSERT INTO resdb_user_account (logon_name, first_name, family_name, status) VALUES ('admin', 'admin', 'admin', 'A');*/
/********************************************************************************************************************************************
** CREATE STANDARD PERMISSIONS
********************************************************************************************************************************************/
-- CONFIGURATION PERMISSIONS
DELETE FROM resdb_permission;
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (2, 'DATA_CLASS_ASSOCIATION-CRU', 'Data class association maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (1, 'DATA_CLASS_ASSOCIATION-CRUD', 'Data class association maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (3, 'DATA_CLASS_ASSOCIATION-R', 'Data class association query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (4, 'MENU_CONFIGURATION-CRUD', 'Menu configuration maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (5, 'MENU_CONFIGURATION-CRU', 'Menu configuration maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (6, 'MENU_CONFIGURATION-R', 'Menu configuration configuration query', 'A', 'C');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (7, 'RESET_PASSWORD', 'Reset Password', 'A', 'U');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (8, 'MENU-CRUD', 'Menu maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (9, 'MENU-CRU', 'Menu maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (10, 'MENU-R', 'Menu query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (11, 'MENU_OPTION-CRUD', 'Menu option maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (12, 'MENU_OPTION-CRU', 'Menu option maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (13, 'MENU_OPTION-R', 'Menu option query', 'A', 'R');
-- USER_ADMIN PERMISSIONS
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (14, 'USER_ACCOUNT_MAINTENANCE-CRUD', 'User account maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (15, 'USER_ACCOUNT_MAINTENANCE-CRU', 'User account maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (16, 'USER_ACCOUNT_MAINTENANCE-R', 'User account query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (17, 'USER_GROUP_MAINTENANCE-CRUD', 'User group maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (18, 'USER_GROUP_MAINTENANCE-CRU', 'User group maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (19, 'USER_GROUP_MAINTENANCE-R', 'User group query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (20, 'USER_PASSWORD_MAINTENANCE-CRUD', 'User password maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (21, 'USER_PASSWORD_MAINTENANCE-CRU', 'User password maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (22, 'USER_PASSWORD_MAINTENANCE-R', 'User password query', 'A', 'R');
-- SYSTEM_ADMIN PERMISSIONS
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (23, 'SYSTEM_PARAMETERS', 'System Parameters', 'A', 'CRUD');
-- DATA_MAINTENANCE PERMISSIONS
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (24, 'ADDRESS_TYPE-CRUD', 'Address types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (25, 'ADDRESS_TYPE-R', 'Address types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (26, 'ARTEFACT_ATTRIBUTE_TYPE-CRUD', 'Artefact attribute types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (27, 'ARTEFACT_TYPE-CRUD', 'Artefact types maintenance(Create/Read//Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (28, 'ARTEFACT_ATTRIBUTE_TYPE-CRU', 'Artefact attribute types maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (29, 'ARTEFACT_ATTRIBUTE_TYPE-R', 'Artefact attribute types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (30, 'CALENDAR_TYPE-CRUD', 'Calendar types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (31, 'CALENDAR_TYPE-CRU', 'Calendar types maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (32, 'CALENDAR_TYPE-R', 'Calendar types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (33, 'DEITY_TYPE-CRUD', 'Deity types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (34, 'DEITY_TYPE-R', 'Deity types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (35, 'ENTITY_TYPE-CRUD', 'Entity types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (36, 'ENTITY_TYPE-R', 'Entity types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (37, 'EVENT_TYPE-CRUD', 'Event types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (38, 'EVENT_TYPE-CRU', 'Event types maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (39, 'EVENT_TYPE-R', 'Event types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (40, 'EVENT_ATTRIBUTE_TYPE-CRUD', 'Event attribute types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (41, 'EVENT_ATTRIBUTE_TYPE-CRU', 'Event attribute types maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (42, 'EVENT_ATTRIBUTE_TYPE-R', 'Event attribute types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (43, 'HIERARCHY_TYPE-CRUD', 'Hierarchy types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (44, 'HIERARCHY_TYPE-CRU', 'Hierarchy types maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (45, 'HIERARCHY_TYPE-R', 'Hierarchy Hierarchy types query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (46, 'MEASURE_TYPE-CRUD', 'Measure types maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (47, 'MEASURE_TYPE-CRU', 'Measure types maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (48, 'MEASURE_TYPE-R', 'Measure types query q', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (49, 'PERMISSION-CRUD', 'Permissions maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (50, 'PERMISSION-CRU', 'Permissions maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (51, 'PERMISSION-R', 'Permissions query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (52, 'ARTEFACT_ATTRIBUTE-CRUD', 'Artefact attributes maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (53, 'ARTEFACT_ATTRIBUTE-CRU', 'Artefact attributes maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (54, 'ARTEFACT_ATTRIBUTE-R', 'Artefact attributes query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (55, 'ARTEFACT_GROUP-CRUD', 'Artefact group maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (56, 'ARTEFACT_GROUP-CRU', 'Artefact group maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (57, 'ARTEFACT_GROUP-R', 'Artefact group query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (58, 'ARTEFACT_IMAGE-CRUD', 'Artefact image maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (59, 'ARTEFACT_IMAGE-CRU', 'Artefact image maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (60, 'ARTEFACT_IMAGE-R', 'Artefact image query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (61, 'ARTEFACT_IMG_PATTERN_SMBL-CRUD', 'Artefact image pattern symbol maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (62, 'ARTEFACT_IMG_PATTERN_SMBL-CRU', 'Artefact image pattern symbol maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (63, 'ARTEFACT_IMG_PATTERN_SMBL-R', 'Artefact image pattern symbol query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (64, 'ARTEFACT-CRUD', 'Artefact maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (65, 'ARTEFACT-CRU', 'Artefact maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (66, 'ARTEFACT-R', 'Artefact query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (67, 'ARTEFACT_PLACE-CRUD', 'Artefact place maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (68, 'ARTEFACT_PLACE-CRU', 'Artefact place maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (69, 'ARTEFACT_PLACE-R', 'Artefact place query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (70, 'ARTEFACT_RSTRTN_WORK-CRUD', 'Artefact restoration work maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (71, 'ARTEFACT_RSTRTN_WORK-CRU', 'Artefact restoration work maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (72, 'ARTEFACT_RSTRTN_WORK-R', 'Artefact restoration work query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (73, 'CALENDAR-CRUD', 'Calendar maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (74, 'CALENDAR-CRU', 'Calendar maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (75, 'CALENDAR-R', 'Calendar query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (76, 'CALENDAR_PLACE-CRUD', 'Calendar race maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (77, 'CALENDAR_PLACE-CRU', 'Calendar race maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (78, 'CALENDAR_PLACE-R', 'Calendar race query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (79, 'COUNTRY-CRUD', 'Country maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (80, 'COUNTRY-CRU', 'Country maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (81, 'COUNTRY-R', 'Country query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (82, 'COUNTRY_REGION-CRUD', 'Country region maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (83, 'COUNTRY_REGION-CRU', 'Country region maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (84, 'COUNTRY_REGION-R', 'Country region query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (85, 'DEITY-CRUD', 'Deity maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (86, 'DEITY-CRU', 'Deity maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (87, 'DEITY-R', 'Deity query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (88, 'ENTITY-CRUD', 'Entity maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (89, 'ENTITY-CRU', 'Entity maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (90, 'ENTITY-R', 'Entity query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (91, 'IMAGE_COLLECTION-CRUD', 'Image collection maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (92, 'IMAGE_COLLECTION-CRU', 'Image collection maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (93, 'IMAGE_COLLECTION-R', 'Image collection query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (94, 'IMAGE-CRUD', 'Image maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (95, 'IMAGE-CRU', 'Image maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (96, 'IMAGE-R', 'Image query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (97, 'LANGUAGE_GROUP-CRUD', 'Language group maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (98, 'LANGUAGE_GROUP-CRU', 'Language group maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (99, 'LANGUAGE_GROUP-R', 'Language group query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (100, 'LANGUAGE_LOCATION-CRUD', 'Language location maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (101, 'LANGUAGE_LOCATION-CRU', 'Language location maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (102, 'LANGUAGE_LOCATION-R', 'Language location query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (103, 'LANGUAGE-CRUD', 'Language maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (104, 'LANGUAGE-CRU', 'Language maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (105, 'LANGUAGE-R', 'Language query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (106, 'MATERIAL-CRUD', 'Material maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (107, 'MATERIAL-CRU', 'Material maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (108, 'MATERIAL-R', 'Material query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (109, 'MEASURE-CRUD', 'Material maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (110, 'MEASURE-CRU', 'Material maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (111, 'MEASURE-R', 'Material query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (112, 'PATTERN_SYMBOL-CRUD', 'Pattern symbol maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (113, 'PATTERN_SYMBOL-CRU', 'Pattern symbol maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (114, 'PATTERN_SYMBOL-R', 'Pattern symbol query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (115, 'PERIOD-CRUD', 'Period maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (116, 'PERIOD-CRU', 'Period maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (117, 'PERIOD-R', 'Period query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (118, 'PERSON-CRUD', 'Person maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (119, 'PERSON-CRU', 'Person maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (120, 'PERSON-R', 'Person query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (121, 'PLACE-CRUD', 'Person maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (122, 'PLACE-CRU', 'Person maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (123, 'PLACE-R', 'Person query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (124, 'PUBLICATION-CRUD', 'Publication maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (125, 'PUBLICATION-CRU', 'Publication maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (126, 'PUBLICATION-R', 'Publication query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (127, 'PUBLICATION_ROLE-CRUD', 'Publication role maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (128, 'PUBLICATION_ROLE-CRU', 'Publication role maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (129, 'PUBLICATION_ROLE-R', 'Publication role query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (130, 'RACE-CRUD', 'Race maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (131, 'RACE-CRU', 'Race maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (132, 'RACE-R', 'Race query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (133, 'RACE_ALIAS-CRUD', 'Race alias maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (134, 'RACE_ALIAS-CRU', 'Race alias maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (135, 'RACE_ALIAS-R', 'Race alias query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (136, 'RACE_PLACE-CRUD', 'Race place maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (137, 'RACE_PLACE-CRU', 'Race place maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (138, 'RACE_PLACE-R', 'Race place query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (139, 'REGION-CRUD', 'Region maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (140, 'REGION-CRU', 'Region maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (141, 'REGION-R', 'Region query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (142, 'RELIGION-CRUD', 'Regliion maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (143, 'RELIGION-CRU', 'Religion maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (144, 'RELIGION-R', 'Religion query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (145, 'RIVER-CRUD', 'River maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (146, 'RIVER-CRU', 'River maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (147, 'RIVER-R', 'River query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (148, 'RIVER_ALIAS-CRUD', 'River alias maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (149, 'RIVER_ALIAS-CRU', 'River alias maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (150, 'RIVER_ALIAS-R', 'River alias query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (151, 'TALE-CRUD', 'Tale maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (152, 'TALE-CRU', 'Tale maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (153, 'TALE-R', 'Tale query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (154, 'TECHNOLOGY-CRUD', 'Technology maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (155, 'TECHNOLOGY-CRU', 'Technology maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (156, 'TECHNOLOGY-R', 'Technology query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (157, 'THEORY-CRUD', 'Theory maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (158, 'THEORY-CRU', 'Theory maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (159, 'THEORY-R', 'Theory query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (160, 'TITLE-CRUD', 'Title maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (161, 'TITLE-CRU', 'Title maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (162, 'TITLE-R', 'Title query', 'A', 'R');
-- RESEARCH PERMISSIONS
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (163, 'BIBLIOGRAPHY-CRUD', 'Bibliography maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (164, 'BIBLIOGRAPHY-CRU', 'Bibliography maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (165, 'BIBLIOGRAPHY-R', 'Bibliography query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (166, 'BIBLIOGRAPHY_PUBLICATION-CRUD', 'Bibliography publication maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (167, 'BIBLIOGRAPHY_PUBLICATION-CRU', 'Bibliography publication maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (168, 'BIBLIOGRAPHY_PUBLICATION-R', 'Bibliography publication query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (169, 'HIERARCHY-CRUD', 'Hierarchy maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (170, 'HIERARCHY-CRU', 'Hierarchy maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (171, 'HIERARCHY-R', 'Hierarchy query', 'A', 'R');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (172, 'REFERENCE-CRUD', 'Reference maintenance (Create/Read/Update/Delete)', 'A', 'CRUD');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (173, 'REFERENCE-CRU', 'Reference maintenance (Create/Read/Update)', 'A', 'CRU');
INSERT INTO resdb_permission (id, name, description, status, operation_type) VALUES (174, 'REFERENCE-R', 'Reference query', 'A', 'R');


