CREATE DATABASE IF NOT EXISTS resdb_prod
  DEFAULT CHARACTER_SET_NAMESET = "utf8";

CREATE USER resdb_dbo IDENTIFIED BY 'resdb_dbo'; // identified by is the password
GRANT SELECT,INSERT,UPDATE,DELETE,ALTER,CREATE,CREATE_TEMPORARY_TABLES,CREATE_VIEW,INDEX,DROP,CREATE_TABLESPACE ON resdb_prod.* TO resdb_dbo;

CREATE USER resdb_rw_user IDENTIFIED BY 'resdb_rw_user'; // identified by is the password
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE_TEMPORARY_TABLES,CREATE_ROUTINE,ALTER_ROUTINE ON resdb_prod.* TO resdb_rw_user;

