
logging:
  level:
    org:
      hibernate: ERROR
#        sql: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace
      springframework:
        jdbc: ERROR
        web:
          filter:
            CommonsRequestLoggingFilter: ERROR
    com.apschulewitz.resdb: ERROR
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com:
      mysql:
        cj:
          jdbc:
            ClientPreparedStatement: ERROR

spring:
  datasource:
    sqlScriptEncoding: UTF-8
    sql-script-encoding: UTF-8
    driver: com.mysql.cj.jdbc.Driver
    url: ${RESDB_DB_JDBC_URL}
    username: ${RESDB_DB_USER}
    password: ${RESDB_DB_PASSWORD}
  data:
    rest:
      base-path: /resdb/api
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  session:
    store-type: none

# Database migration tool (see src/main/resources/db/changelog)
  liquibase:
    enabled: true
    user: ${RESDB_DB_USER}
    password: ${RESDB_DB_PASSWORD}
    contexts: ALL, MYSQL, H2

  # Enable zipkin support, sample all requests
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1.0
sample:
  zipkin:
    enabled: true

server:
  port: 8080

client:
  cors:
    base:
      url: http://localhost:50545


environment: dev

authentication:
  expiryInMinutes: 7200

#security:
#  ignored:
#    - "*.bundle.*"
#  sessions: NEVER
