flyway:
#  locations: db/migration/mysql
#  enabled: false
#  locations: database/schema/mysql

logging:
  level:
    org:
      hibernate: ERROR
#        sql: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace
      springframework:
        jdbc: ERROR
        web:
          filter:
            CommonsRequestLoggingFilter: ERROR
    com.apschulewitz.resdb: ERROR
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com:
      mysql:
        cj:
          jdbc:
            ClientPreparedStatement: ERROR

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resdb_dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: resdb_dev
    password: resdb_dev
  data:
    rest:
      base-path: /resdb/api
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  session:
    store-type: none

# Enable zipkin support, sample all requests
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1.0
sample:
  zipkin:
    enabled: true

server:
  port: 8080

client:
  cors:
    base:
      url: http://localhost:50545


environment: dev

authentication:
  expiryInMinutes: 7200

#security:
#  ignored:
#    - "*.bundle.*"
#  sessions: NEVER
